### ISSUE TITLE
PLY file viewer

### ISSUE THREAD

**Issue by tersite1** [tersite1/DepthViz-iOSPPointCloudScanner#1]
I want to visualize pointlcloud output file within app itself but I failed, someone has a idea? 

Thank you.

**Comment by tersite1** [comment]
I FINALLY DID IT HAHAHAHAHAHA

**Comment by tersite1** [comment]
![IMG_3765](https://github.com/user-attachments/assets/39453a31-8d5f-427f-bbe0-471788eb5cf4)

**Comment by gogogo617** [comment]
hello

**Comment by gogogo617** [comment]
Hello, when I was reading satnerf today, I found your comment, I feel that our research direction is very similar, can you add a contact information to make a friend?

**Comment by tersite1** [comment]
> Hello, when I was reading satnerf today, I found your comment, I feel that our research direction is very similar, can you add a contact information to make a friend?

Hello, I appreciate for you interest. You can Check my Linked or contact my email. 

linkedin : https://www.linkedin.com/in/jadenjang/
email : itcouldbe0@yonsei.ac.kr
